version: "3.8"
services:
  backend_db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
